UnwindTerminateReason in std::intrinsics::mir - Rust
std
::
intrinsics
::
mir
Enum
UnwindTerminateReason
Copy item path
Source
pub enum UnwindTerminateReason {
    Abi,
    InCleanup,
}
๐ฌ
This is a nightly-only experimental API. (
custom_mir
)
Expand description
The reason we are terminating the process during unwinding.
Variants
ยง
ยง
Abi
๐ฌ
This is a nightly-only experimental API. (
custom_mir
)
Unwinding is just not possible given the ABI of this function.
ยง
InCleanup
๐ฌ
This is a nightly-only experimental API. (
custom_mir
)
We were already cleaning up for an ongoing unwind, and a
second
,
nested
unwind was
triggered by the drop glue.
Auto Trait Implementations
ยง
ยง
impl
Freeze
for
UnwindTerminateReason
ยง
impl
RefUnwindSafe
for
UnwindTerminateReason
ยง
impl
Send
for
UnwindTerminateReason
ยง
impl
Sync
for
UnwindTerminateReason
ยง
impl
Unpin
for
UnwindTerminateReason
ยง
impl
UnwindSafe
for
UnwindTerminateReason
Blanket Implementations
ยง
Source
ยง
impl<T>
Any
for T
where
    T: 'static + ?
Sized
,
Source
ยง
fn
type_id
(&self) ->
TypeId
Gets the
TypeId
of
self
.
Read more
Source
ยง
impl<T>
Borrow
<T> for T
where
    T: ?
Sized
,
Source
ยง
fn
borrow
(&self) ->
&T
Immutably borrows from an owned value.
Read more
Source
ยง
impl<T>
BorrowMut
<T> for T
where
    T: ?
Sized
,
Source
ยง
fn
borrow_mut
(&mut self) ->
&mut T
Mutably borrows from an owned value.
Read more
Source
ยง
impl<T>
From
<T> for T
Source
ยง
fn
from
(t: T) -> T
Returns the argument unchanged.
Source
ยง
impl<T, U>
Into
<U> for T
where
    U:
From
<T>,
Source
ยง
fn
into
(self) -> U
Calls
U::from(self)
.
That is, this conversion is whatever the implementation of
From
<T> for U
chooses to do.
Source
ยง
impl<T, U>
TryFrom
<U> for T
where
    U:
Into
<T>,
Source
ยง
type
Error
=
Infallible
The type returned in the event of a conversion error.
Source
ยง
fn
try_from
(value: U) ->
Result
<T, <T as
TryFrom
<U>>::
Error
>
Performs the conversion.
Source
ยง
impl<T, U>
TryInto
<U> for T
where
    U:
TryFrom
<T>,
Source
ยง
type
Error
= <U as
TryFrom
<T>>::
Error
The type returned in the event of a conversion error.
Source
ยง
fn
try_into
(self) ->
Result
<U, <U as
TryFrom
<T>>::
Error
>
Performs the conversion.